version: '2'
services:
  postgis:
    build: ./postgis
    volumes:
      # mount
      - ./data-osm-pbf/oberbayern-latest.osm.pbf:/region.osm.pbf
      # volume
      - postgis-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_PASSWORD=offline-osm
    ports:
      # - "127.0.0.1:5432:5432"
      - "5432:5432"
  renderer:
    build: ./renderer
    volumes:
      - ./renderer/map_data/config.json:/map_data/config.json
      - ./renderer/map_data/stylesheet.xml:/openstreetmap-carto/stylesheet.xml
      - ./renderer/scripts:/scripts
    volumes_from:
      - postgis:ro
    ports:
      # - "127.0.0.1:7007:8080"
      # - "127.0.0.1:7008:9090"
      - "7007:8080"
      - "7008:9090"
    depends_on:
      - postgis
  web:
    image: nginx:1.11-alpine
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      # - "127.0.0.1:7009:80"
      - "7009:80"

volumes:
  postgis-data: