version: '2'
services:
  postgis:
    build: ./postgis
    volumes:
      - ./data-osm-pbf/oberbayern-latest.osm.pbf:/region.osm.pbf
    #   - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_PASSWORD=offline-osm
    ports:
      - "127.0.0.1:5432:5432"
  renderer:
    build: ./renderer
    volumes:
      - ./renderer/map_data:/map_data
      - ./renderer/scripts:/scripts
    volumes_from:
      - postgis:ro
    ports:
      - "127.0.0.1:7007:8080"
      - "127.0.0.1:7008:9090"
    depends_on:
      - postgis
  web:
    image: nginx:1.11-alpine
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - "127.0.0.1:7000:80"
